### ISSUE TITLE
Error while running ./run.sh file ( recipe 2 - Hindi_english )

### ISSUE THREAD

**Issue by Shalini-lodhi** [Shalini-lodhi/Speech-Recognition#1]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

**_We faced the following error after we ran run.sh file ( in Running the Baseline script column of README.md ) . After completion of all the other command lines successfully ._**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

Preparing data and training language models
Preparing train and test data
copy wav.scp for train test
copy files from corpus/data to data/ for train test
Preparing data OK.
Dictionary preparation succeeded
utils/prepare_lang.sh data/local/dict <unk> data/local/lang data/lang
Checking data/local/dict/silence_phones.txt ...
--> reading data/local/dict/silence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/silence_phones.txt is OK

Checking data/local/dict/optional_silence.txt ...
--> reading data/local/dict/optional_silence.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/optional_silence.txt is OK

Checking data/local/dict/nonsilence_phones.txt ...
--> reading data/local/dict/nonsilence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/nonsilence_phones.txt is OK

Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> disjoint property is OK.

Checking data/local/dict/lexicon.txt
--> reading data/local/dict/lexicon.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/lexicon.txt is OK

Checking data/local/dict/lexiconp.txt
--> reading data/local/dict/lexiconp.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/lexiconp.txt is OK

Checking lexicon pair data/local/dict/lexicon.txt and data/local/dict/lexiconp.txt
--> lexicon pair data/local/dict/lexicon.txt and data/local/dict/lexiconp.txt match

Checking data/local/dict/extra_questions.txt ...
--> data/local/dict/extra_questions.txt is empty (this is OK)
--> SUCCESS [validating dictionary directory data/local/dict]

fstcompile: error while loading shared libraries: libfstscript.so.16: cannot open shared object file: No such file or directory
fstarcsort: error while loading shared libraries: libfstscript.so.16: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "utils/lang/make_lexicon_fst.py", line 411, in <module>
    main()
  File "utils/lang/make_lexicon_fst.py", line 401, in main
    left_context_phones=left_context_phones)
  File "utils/lang/make_lexicon_fst.py", line 294, in write_fst_with_silence
    cost=sil_cost + (pron_cost if i <= 0 else 0.0)))
BrokenPipeError: [Errno 32] Broken pipe
local/prepare_lm.sh: line 11: ngram-count: command not found
arpa2fst: error while loading shared libraries: libkaldi-lm.so: cannot open shared object file: No such file or directory
steps/make_mfcc.sh --nj 10 --cmd run.pl data/train exp/make_mfcc/train mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/train
steps/make_mfcc.sh [info]: segments file exists: using that.
run.pl: 10 / 10 failed, log is in exp/make_mfcc/train/make_mfcc_train.*.log
steps/compute_cmvn_stats.sh data/train exp/make_mfcc/train mfcc
steps/compute_cmvn_stats.sh: no such file data/train/feats.scp
steps/make_mfcc.sh --nj 10 --cmd run.pl data/test exp/make_mfcc/test mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/test
steps/make_mfcc.sh [info]: segments file exists: using that.
run.pl: 10 / 10 failed, log is in exp/make_mfcc/test/make_mfcc_test.*.log
steps/compute_cmvn_stats.sh data/test exp/make_mfcc/test mfcc
steps/compute_cmvn_stats.sh: no such file data/test/feats.scp
mono training
steps/train_mono.sh --nj 10 --cmd run.pl data/train data/lang exp/mono
cat: data/lang/oov.int: No such file or directory
mono training done
mono decoding on test
tri1 training
steps/align_si.sh --nj 10 --cmd run.pl data/train data/lang exp/mono exp/mono_ali
mkgraph.sh: expected data/lang/L_disambig.fst to exist
steps/decode.sh --nj 24 --cmd run.pl exp/mono/graph data/test exp/mono/decode_test
steps/align_si.sh: expected file data/lang/oov.int to exist
steps/train_deltas.sh --boost-silence 1.25 --cmd run.pl 2000 20000 data/train data/lang exp/mono_ali exp/tri1
train_deltas.sh: no such file exp/mono_ali/final.mdl
tri1 training done
tri1 decoding on test
tri2b training
steps/decode.sh: Error: no such file data/test/split24/1/feats.scp
mono decoding on test done
steps/align_si.sh --nj 10 --cmd run.pl data/train data/lang exp/tri1 exp/tri1_ali
mkgraph.sh: expected data/lang/L_disambig.fst to exist
steps/decode.sh --nj 24 --cmd run.pl exp/tri1/graph data/test exp/tri1/decode_test
steps/align_si.sh: expected file data/lang/oov.int to exist
steps/train_lda_mllt.sh --cmd run.pl --splice-opts --left-context=3 --right-context=3 2500 15000 data/train data/lang exp/tri1_ali exp/tri2b
train_lda_mllt.sh: no such file exp/tri1_ali/final.mdl
tri2b training done
steps/decode.sh: Error: no such file data/test/split24/1/feats.scp
tri2b decoding on test
tri1 decoding on test done.
tri3b training
steps/align_si.sh --nj 10 --cmd run.pl data/train data/lang exp/tri2b exp/tri2b_ali
mkgraph.sh: expected data/lang/L_disambig.fst to exist
steps/decode.sh --nj 24 --cmd run.pl exp/tri2b/graph data/test exp/tri2b/decode_test
steps/align_si.sh: expected file data/lang/oov.int to exist
steps/train_sat.sh --cmd run.pl 2500 15000 data/train data/lang exp/tri2b_ali exp/tri3b
train_sat.sh: no such file data/train/feats.scp
tri3b training done
tri3b decoding on test
tri4b training
steps/align_fmllr.sh --nj 10 --cmd run.pl data/train data/lang exp/tri3b exp/tri3b_ali
steps/decode.sh: Error: no such file data/test/split24/1/feats.scp
tri2b decoding on test done.
mkgraph.sh: expected data/lang/L_disambig.fst to exist
steps/decode_fmllr.sh --nj 24 --cmd run.pl exp/tri3b/graph data/test exp/tri3b/decode_test
cat: data/lang/oov.int: No such file or directory
steps/train_sat.sh --cmd run.pl 4200 40000 data/train data/lang exp/tri3b_ali exp/tri4b
train_sat.sh: no such file data/train/feats.scp
tri4b training done
tri4b decoding on test
local/chain/run_tdnn.sh --stage 0 --nj 10 --decode_nj 24
mkgraph.sh: expected data/lang/L_disambig.fst to exist
steps/decode_fmllr.sh --nj 24 --cmd run.pl exp/tri4b/graph data/test exp/tri4b/decode_test
local/nnet3/run_ivector_common.sh: expected file data/train/feats.scp to exist
filter_scps.pl: warning: some input lines did not get output
cat: exp/tri4b/graph/phones/silence.csl: No such file or directory
tri4b decoding on test done.
Could not open id-list file data/test/split24/1/tmp.reco at utils/filter_scps.pl line 99.
tri3b decoding on test done.

grep: exp/mono/decode_test/wer_*: No such file or directory
grep: exp/tri1/decode_test/wer_*: No such file or directory
grep: exp/tri2b/decode_test/wer_*: No such file or directory
grep: exp/tri3b/decode_test/wer_*: No such file or directory
grep: exp/tri4b/decode_test/wer_*: No such file or directory

**Comment by s-mousmita** [comment]
fstcompile: error while loading shared libraries: libfstscript.so.16: cannot open shared object file: No such file or directory
fstarcsort: error while loading shared libraries: libfstscript.so.16: cannot open shared object file: No such file or directory
Traceback (most recent call last):

It looks like your openfst installation went wrong or you are not using opnfst while configuring kaldi/src. A third possibility could be you have some issue in path.sh.

**Comment by s-mousmita** [comment]
export PATH=$PWD/utils/:$KALDI_ROOT/tools/openfst/bin
Do you have such a line in your path.sh.
If no you should add that.
Secondly, try to make openfst in your kaldi/tools again.

**Comment by Shalini-lodhi** [comment]
ma'am can you please help/explain us the `local/gen_wavscp.sh folder < old_wavscp > new_wavscp` step in [Changing paths in wav.scp](https://github.com/navana-tech/baseline_recipe_is21s_indic_asr_challenge/tree/master/is21-subtask2-kaldi#changing-paths-in-wavscp) step.

we have copied the transcript folder from the data set to the corpus folder and renamed it to test and train respectively and in the folder the required files were auto generated; as instructed in the last step of [Data Setup Instructions](https://github.com/navana-tech/baseline_recipe_is21s_indic_asr_challenge/tree/master/is21-subtask2-kaldi#data-setup-instructions)

**Comment by digvijaysrisai** [comment]
> ma'am can you please help/explain us the `local/gen_wavscp.sh folder < old_wavscp > new_wavscp` step in [Changing paths in wav.scp](https://github.com/navana-tech/baseline_recipe_is21s_indic_asr_challenge/tree/master/is21-subtask2-kaldi#changing-paths-in-wavscp) step.
> 
> we have copied the transcript folder from the data set to the corpus folder and renamed it to test and train respectively and in the folder the required files were auto generated; as instructed in the last step of [Data Setup Instructions](https://github.com/navana-tech/baseline_recipe_is21s_indic_asr_challenge/tree/master/is21-subtask2-kaldi#data-setup-instructions)

Try installing 'awk' once.....
